---
services:

##NEWLINE##
  web:
    git_url: http://github.com/checkraiser/test_rails
    git_branch: 
    command: bundle exec rails server -e _env:RAILS_ENV
    build_command: /bin/sh -c "RAILS_ENV=_env:RAILS_ENV bundle exec rake db:schema:load"
    deploy_command: /bin/sh -c "RAILS_ENV=_env:RAILS_ENV bundle exec rake db:migrate"
    build_root: cloud/test_rails/

    ports:
      - container: 3000
        http: 80
        https: 443
        
        
    

    env_vars:
      RAILS_ENV: production
    
      RACK_ENV: production
    



##NEWLINE##
databases:
  - postgresql